regions = {
    "Blekinge": "DGQd_uYs_oKb",
    "Dalarna": "oDpK_oZ2_WYt",
    "Gotland": "K8iD_VQv_2BA",
    "Gavleborg": "zupA_8Nt_xcD",
    "Halland": "wjee_qH2_yb6",
    "Jamtland": "65Ms_7r1_RTG",
    "Jonkoping": "MtbE_xWT_eMi",
    "Kalmar": "9QUH_2bb_6Np",
    "Kronoberg": "tF3y_MF9_h5G",
    "Norrbotten": "9hXe_F4g_eTG",
    "Skane": "CaRE_1nn_cSU",
    "Stockholm": "CifL_Rzy_Mku",
    "Sodermanland": "s93u_BEb_sx2",
    "Uppsala": "zBon_eET_fFU",
    "Varmland": "EVVp_h6U_GSZ",
    "Vasterbotten": "g5Tt_CAV_zBd",
    "Vasternorrland": "NvUF_SP1_1zo",
    "Vastmanland": "G6DV_fKE_Viz",
    "Vastra Gotaland": "zdoY_6u5_Krt",
    "Orebro": "xTCk_nT5_Zjm",
    "Ostergotland": "oLT3_Q9p_3nn",
}

